### ISSUE TITLE
Feature: Add a command to add a movie to both A and B lists

### ISSUE THREAD

**Issue by digglesby** [redactedaccount/PashaBot#1]
### Why 
Some people have requested movies that fall in both the A and B lists. It would be nice to be able to do this in a single command versus adding it to the A list and B list sequentially.

### How 
An example command might look like `!addmovie AB: Movie Name`

**Comment by redactedaccount** [comment]
Great idea. Debating on whether or not I should make this extensible by making a table that defines each movie type and allow users to define their own movie type, or K.I.S.S and just define A and B in the docs and help commands.

**Comment by digglesby** [comment]
> Great idea. Debating on whether or not I should make this extensible by making a table that defines each movie type and allow users to define their own movie type, or K.I.S.S and just define A and B in the docs and help commands.

I'm a big fan of emergent requirements, if people ask for it or there's a need for metadata about the A and B lists add it. If not, we're probably good with just a dumb varchar field A or B.

**Comment by redactedaccount** [comment]
Yeah, simplicity is good. I could show off by extending this.. and it would be fun, but ultimately I think it would just be over engineering the feature.  No one wants to read a bunch of documentation just to figure out how to properly add a movie for a movie roulette.

There is one interesting problem that arises with this:  To make it 'AB' and update `random_movie()` to also pick from 'AB' movies for either choice, or to make duplicates.

With duplicates, it only takes it out of one list and the movie can be chosen again.

With 'AB', the movie can only be chosen once.

I'm leaning towards 'AB', because we're creatures of novelty.
